spring:
  security:
    user:
      name: buzz
      password: infinity
  data:
    rest:
      base-path: /api

taco:
  orders:
    pageSize: 10

logging:
  level:
    tacos: DEBUG


#server:
#  servlet:
#    context-path: /patry

---
spring:
  profiles: prod

  datasource:
    url: jdbc:mysql://localhost/tacocloud
    username: tacouser
    password: tacopassword

logging:
  level:
    tacos: WARN