# The values given here are actually the default values. But they are explicitly
# set here as an example of setting the Kafka properties.
#spring:
#  kafka:
#    bootstrap-servers:
#      #- localhost:2181
#      - localhost:9092
#    template:
#      default-topic: tacocloud
#      #default-topic: tacocloud.orders.topic
#    producer:
#      keySerializer: org.springframework.kafka.support.serializer.JsonSerializer
#      valueSerializer: org.springframework.kafka.support.serializer.JsonSerializer

# not needed because we use application.yml from tacos module