server:
  port: 8081

---
spring:
  profiles:
    active: kafka-listener
  #  profiles: jms-template, jms-listener
  #  profiles: rabbitmq-template, rabbitmq-listener
  #  profiles: kafka-listener

  # The values given here are actually the default values. But they are explicitly
  # set here as an example of setting the Artemis properties.
  jms:
    template:
      default-destination: tacocloud.order.queue
      #receive-timeout: 2
  artemis:
    host: localhost
    port: 61616
    user: tacoweb
    password: letm31n
    embedded:
      enabled: false

  rabbitmq:
    template:
      exchange: tacocloud.orders
      #routing-key: tacocloud.order.queue
      receive-timeout: 3000
      #default-queue: tacocloud.order.queue

  kafka:
    bootstrap-servers:
      - localhost:9092
    template:
      default-topic: tacocloud.orders.topic
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: tacocloud_kitchen
      properties:
        spring.json.trusted.packages: tacos
